import type { Metadata } from 'next'
import './globals.css'
import { Kanit } from 'next/font/google'
import { LayoutContextProvider } from '@/contexts/Layout'

const kanit = Kanit({
  subsets: ['thai'],
  display: 'fallback',
  weight: '300',
})

export const metadata: Metadata = {
  title: 'Youtube Music',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/next.svg" />
      <body suppressHydrationWarning className={kanit.className}>
        <LayoutContextProvider>{children}</LayoutContextProvider>
      </body>
    </html>
  )
}
